version: "3.9"

services:
  web:
    build: .\src\GameGate.ApiGateWay\\Dockerfile
    ports:
      - "8079:8080"
- 
C:\Users\akish\OneDrive\Desktop\Проекты\Новая папка\GameGate\src\GameGate.ApiGateWay\ApiGateWay